package Core.Application.Port.OpenDota.Model

case class Match (
     match_id: Long,
     barracks_status_dire: Int,
     barracks_status_radiant: Int,
     chat: Option[List[Chat]],
     cluster: Int,
     cosmetics: Option[Map[String, Int]], // TODO
     dire_score: Int,
     dire_team_id: Option[Int],
     draft_timings: Option[List[DraftTiming]],
     duration: Int,
     engine: Int,
     first_blood_time: Int,
     game_mode: Int,
     human_players: Int,
     leagueid: Int,
     lobby_type: Int,
     match_seq_num: Long,
     negative_votes: Int,
     objectives: Option[List[Objective]], // TODO
     picks_bans: List[PickBan],
     positive_votes: Int,
     radiant_gold_adv: Option[List[Int]],
     radiant_score: Int,
     radiant_team_id: Option[Long],
     radiant_win: Boolean,
     radiant_xp_adv: Option[List[Int]],
     skill: Option[Int],
     start_time: Int,
     teamfights: Option[List[TeamFights]],
     tower_status_dire: Int,
     tower_status_radiant: Int,
     version: Option[Int],
     replay_salt: Int,
     series_id: Int,
     series_type: Int,
     league: League,
     radiant_team: Option[Team],
     dire_team: Option[Team],
     players: List[Player], // TODO
     patch: Int,
     region: Option[Int],
     //    all_word_counts: Map[String, Int],
     //    my_word_counts: Map[String, Int],
     comeback: Option[Int],
     stomp:  Option[Int],
     replay_url: String
)