package Core.Application.Port.OpenDota.Model

case class Player(
    match_id: Long,
    player_slot: Int,
    ability_targets: Map[String, Map[String, Int]],
    ability_upgrades_arr: List[Int],
    ability_uses: Map[String, Int],
    account_id: Long,
    actions: Map[Int, Int],
//    additional_units: Option[String], // TODO - MatchSample 6
    assists: Int,
    backpack_0: Int,
    backpack_1: Int,
    backpack_2: Int,
    buyback_log: List[BuyBackLog],
    camps_stacked: Int,

    // connection_log,

    creeps_stacked: Int,
    damage: Map[String, Int],
    damage_inflictor: Map[String, Int],
    damage_inflictor_received: Map[String, Int],
    damage_taken: Map[String, Int],
    damage_targets: Map[String, Map[String, Int]],
    deaths: Int,
    denies: Int,
    dn_t: List[Int],
    firstblood_claimed: Int,
    gold: Int,
    gold_per_min: Int,
    gold_reasons: Map[Int, Double],
    gold_spent: Int,
    gold_t: List[Int],

    // End of by hand
    hero_damage: Int,
    hero_healing: Int,
    hero_id: Int,
    item_0: Int,
    item_1: Int,
    item_2: Int,
    item_3: Int,
    item_4: Int,
    item_5: Int,
    kills: Int,
    last_hits: Int,
    leaver_status: Int,
    level: Int,
    obs_placed: Int,
    party_id: Int,
    party_size: Int,
    performance_others: Option[String],
    permanent_buffs: Option[List[Map[String, Int]]],
    pings: Option[Int],
    pred_vict: Boolean,
    randomed: Boolean,
    repicked: Option[Boolean],
    roshans_killed: Int,
    rune_pickups: Int,
    sen_placed: Int,
    stuns: BigDecimal,
    teamfight_participation: BigDecimal,
    tower_damage: Int,
    towers_killed: Int,
    xp_per_min: Int,
    personaname: Option[String],
    name: Option[String],
    last_login: Option[String],
    radiant_win: Boolean,
    start_time: Int,
    duration: Int,
    cluster: Int,
    lobby_type: Int,
    game_mode: Int,
    is_contributor: Boolean,
    patch: Int,
    region: Option[Int],
    isRadiant: Boolean,
    win: Int,
    lose: Int,
    total_gold: Int,
    total_xp: Int,
    kda: Int,
    abandons: Int,
    neutral_kills: Int,
    tower_kills: Int,
    courier_kills: Int,
    lane_kills: Int,
    hero_kills: Int,
    observer_kills: Int,
    sentry_kills: Int,
    roshan_kills: Int,
    necronomicon_kills: Int,
    ancient_kills: Int,
    buyback_count: Int,
    observer_uses: Int,
    sentry_uses: Int,
    lane_efficiency: BigDecimal,
    lane_efficiency_pct: Int,
    lane: Int,
    lane_role: Int,
    is_roaming: Boolean,
    purchase_tpscroll: Int,
    actions_per_min: Int,
    life_state_dead: Int,
    rank_tier: Option[Int]
)
